version: '3.7'
networks:
    mynet:
        name: mynet
services:
  app:
    build: .
    container_name: todolist
    image: todolist:latest
    ports:
      - 8080:8080
    env_file: ./.env
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/cognixus?useSSL=false
    networks:
      - mynet