version: '3.3'
services:
  app: 
    container_name: todolist
    image: todolist:0.0.1
    build: ./
    env_file: ./.env
    ports: 
      - "8080:8080"
    networks:
      - test-network
networks:
  test-network:
    name: test-network